### ISSUE TITLE
Add `Expr.map_elements(...)` functionality

### ISSUE THREAD

**Issue by DeflateAwning** [ankane/ruby-polars#66]
Python and Rust Polars both prefer `map_elements` to `apply`, and have a deprecation warning.

At the very least, I think that `.map_elements` should work and should be in the doc.

**Comment by DeflateAwning** [comment]
Upon further inspection, I'm getting errors like `NoMethodError (undefined method `apply' for col("date_min"):Polars::Expr)` while trying:

```ruby
                  df.with_columns(
                    date: Polars.col('date_min').apply {|date_min| Polars.date_range(date_min, date_max, "1mo")}
                  )
```

Looking at the docs, I see `DataFrame.apply` and `Series.apply`, but no `XxxExpr.apply`. I think maybe those function mappings/implementations were missed entirely. Wondering if they could be added?

**Comment by ankane** [comment]
Hi @DeflateAwning, `Series` already has `map_elements`, and I aliased `DataFrame#apply` to `map_rows` in 6b8c9b42a8e8680509cf9e7cc572890ec74192d7. I haven't been able to get `Expr#map_elements`/`Expr#apply` to work without crashing, but someone is welcome to submit a PR if they're able to.

**Comment by ankane** [comment]
Spent some more time on this ([expr-map-elements branch](https://github.com/ankane/ruby-polars/compare/expr-map-elements)), and as far I as can tell, this can't currently be done (Polars Rust creates its own threads, but you can't call Ruby from non-Ruby threads).

I think `Series#map_elements` and `DataFrame#map_rows` will work for most cases.

**Comment by DeflateAwning** [comment]
Hmm, is there anything we can request in another project (Rust Polars or the interop library)? Or some sort of hack that uses the map_row mechanism to add a new column? Maybe we could leave this open as a central place to discuss this rather-notable deficiency?
