### ISSUE TITLE
Handle something like `filter{|row| row.a > 2 && row.b.nil? }`

### ISSUE THREAD

**Issue by turnon** [ankane/ruby-polars#71]
Shall we add such feature ?

convert:

`filter{|row| row.a > 2 && row.b.nil? }`

to:

`filter((Polars.col("a") > 2) & (Polars.col("b").is_null))`

I just think it more like usual ruby code....

**Comment by DeflateAwning** [comment]
This is a pretty big ask, and isn't really at all how Polars is meant to work.

While it might be possible, it strays pretty far from the well-established, cross-language interface Polars has created.

**Comment by ankane** [comment]
Hi @turnon, thanks for the suggestion. It's an interesting idea, but I'd like to keep the API consistent with Python for now.
