### ISSUE TITLE
Implementation: add support for kwargs and/or hash as arg to `Polars.struct`

### ISSUE THREAD

**Issue by DeflateAwning** [ankane/ruby-polars#73]
I think the following syntax should work to create named fields in a struct in an Expression.

```ruby
df = df.select(
    Polars::col('id'),
    test_struct: Polars.struct({
        entity: Polars::col("raw_upper_formation_name"),
        boundary: Polars::col("upper_boundary_type"),
      }),
)
```

I think it should work with OR without curly braces around the Polars.struct arg. I think it should definitely work at least one way like that.

**Comment by ankane** [comment]
Hi @DeflateAwning, updated in the commit above.

**Comment by DeflateAwning** [comment]
No way, thanks so much!
