### ISSUE TITLE
Request: Tag github releases which contain basic release notes

### ISSUE THREAD

**Issue by DeflateAwning** [ankane/ruby-polars#76]
It would be awesome if this library tagged GitHub Release notes, which at the very least mentioned the Rust Polars version number (and link to associated change log). Would make upgrading a little easier/high-confidence!

Thanks again for maintaining such an awesome library :)

**Comment by ankane** [comment]
Hi @DeflateAwning, thanks for the suggestion, but I prefer to use Git tags for releases and the changelog for release notes.
