### ISSUE TITLE
Docs: Add example of using `StringCache`

### ISSUE THREAD

**Issue by DeflateAwning** [ankane/ruby-polars#78]
It would be awesome if there was an example of how the StringCache works on the [StringCache docs page](https://www.rubydoc.info/gems/polars-df/Polars/StringCache)

The comment talks about "context managers", which I assume are copied directly from the Python docs. As Ruby doesn't have context managers though, I assume this would need to be exchanged for a closure in the explanation.

**Comment by ankane** [comment]
Hi @DeflateAwning, added in the commit above.

**Comment by DeflateAwning** [comment]
Thanks for adding this!

I was mostly under the impression that I could stick a bunch of operations inside that `do` block. 

However, I get this error:

```
web-1      | NoMethodError (undefined method `group_by' for #<Polars::StringCache:0x000075d912edfbf0>):
```

Any advice? Should I make a new issue with a reproducable example?

**Comment by ankane** [comment]
A reproducible example would be good.
