### ISSUE TITLE
Request: Implement `_dump_data` so that `Rails.cache` can wrap a DataFrame

### ISSUE THREAD

**Issue by DeflateAwning** [ankane/ruby-polars#79]
Request: Implement `_dump_data` so that `Rails.cache` can wrap a DataFrame

Currently, the following error is returned:
```
TypeError (no _dump_data is defined for class Polars::RbDataFrame):
```

Test case (roughly, may require some rework)

```ruby
  def call
    cache_key = "expensive_operation_1"
    Rails.cache.fetch(cache_key, expires_in: 6.hour) do
      call_no_cache_expensive_operation_1 # Returns a dataframe
    end
  end
```

**Comment by ankane** [comment]
Hi @DeflateAwning, I'm not sure I'd like to support marshal serialization (as it's not secure for untrusted data), but you could add it to your own application with:

```ruby
class Polars::DataFrame
  def _dump(level)
    write_ipc(nil)
  end

  def self._load(bin)
    Polars.read_ipc(StringIO.new(bin))
  end
end
```

**Comment by DeflateAwning** [comment]
Hmm, even with that, I'm still getting `TypeError (no _dump_data is defined for class Polars::RbDataFrame):`
