### ISSUE TITLE
Request: Add support for `df.write_ipc` and `df.write_parquet` (with no args, and with StringIO/BytesIO args)

### ISSUE THREAD

**Issue by DeflateAwning** [ankane/ruby-polars#80]
Modern Python polars supports calling write_ipc with no args (i.e., `file = nil`); the bytes are then returned directly. Would be awesome to support that here.

Same thing for df.write_parquet, except writing to a StringIO/BytesIO

**Comment by ankane** [comment]
Hi @DeflateAwning, this is already possible.

```ruby
io = StringIO.new

df.write_ipc(io)
# or
df.write_parquet(io)
```

**Comment by DeflateAwning** [comment]
Thank you! I was on v0.13.0, and I don't think it was working on that one. Seems good now though (on v0.14.0).
