### ISSUE TITLE
Request: Add support for `schema` kwarg in DataFrame constructor

### ISSUE THREAD

**Issue by DeflateAwning** [ankane/ruby-polars#81]
Request: Add support for `schema` kwarg in DataFrame constructor

The following code:
```ruby
    df = Polars::DataFrame.new(
      result_rows,
      columns: parquet_column_list,
      orient: 'row', # Array-of-rows format.
      schema: parquet_schema
    )
```

Yields this error:
```
Polars::Todo (not implemented yet):
```

**Comment by ankane** [comment]
Hi @DeflateAwning, what's the format of `parquet_schema`? It should work if you pass a hash.

**Comment by ankane** [comment]
Added support for `schema: [["col1", Polars::Float32], ["col2", Polars::Int8]]` in the commit above.

Also, `columns` is an alias for `schema` (`columns` is ignored when both are passed).

**Comment by DeflateAwning** [comment]
The `parquet_schema` arg was indeed a hash; strange it didn't work. Will have to test again!
