### ISSUE TITLE
Docs: Add example of using Enum datatype

### ISSUE THREAD

**Issue by DeflateAwning** [ankane/ruby-polars#85]
Docs page: https://www.rubydoc.info/gems/polars-df/Polars/Enum

It would be awesome if you added an example of how to use the Enum type! 

Thanks!

**Comment by ankane** [comment]
Hi @DeflateAwning, check out https://docs.pola.rs/user-guide/expressions/categorical-data-and-enums/.

**Comment by DeflateAwning** [comment]
For sure! It could be that I'm way more experienced in Python, and don't have an intuitive understanding of what equivalent code looks like in Ruby, but I couldn't figure it out (hence opening this issue).

The following attempts didn't seem to work for me:

```ruby
Polars::Enum(['val1', 'val2'])
Polars.Enum(['val1', 'val2'])
Polars::Enum.initialize(['val1', 'val2'])
```

Can you offer advice? I maintain that a tiny example of the syntax in the docs would be valuable.

**Comment by ankane** [comment]
The way to initialize a class in Ruby is with `new`.

```ruby
Polars::Enum.new(["val1", "val2"])
```

**Comment by DeflateAwning** [comment]
Would you mind adding that as a one-sentence example in the docs?
