### ISSUE TITLE
Any plans to add Delta Lake support

### ISSUE THREAD

**Issue by simpl1g** [ankane/ruby-polars#87]
Python bindings support methods like `read/scan/write_delta`
https://docs.pola.rs/api/python/dev/reference/api/polars.DataFrame.write_delta.html

Do you think it is possible to implement them for Ruby? Previously there were some Ruby bindings for `delta-rs` but they were unmaitened and eventually dropped https://github.com/delta-io/delta-rs/pull/1102

**Comment by ankane** [comment]
Hi @simpl1g, thanks for sharing. I don't have any plans for it, but someone could probably create a separate gem.

**Comment by ankane** [comment]
Hey @simpl1g, just created a [separate gem](https://github.com/ankane/delta-ruby?tab=readme-ov-file) for this that works with the latest release (0.15.0).

There aren't currently precompiled versions, but plan to add them in a future release. Also, it doesn't currently work with string columns, but should when the next release of the Rust library is out (https://github.com/delta-io/delta-rs/pull/2886). Feel free to create an issue if you need any missing functionality.

Will also add `read/scan/write_delta` methods to this library in a future release.

**Comment by simpl1g** [comment]
Wow, you are superhuman :) Do you have special LLM to convert Python bindings to Ruby?)
