### ISSUE TITLE
Limits not applied correctly with Lazy Dataframe

### ISSUE THREAD

**Issue by brettshollenberger** [ankane/ruby-polars#89]
Hey Andrew, haven't had time to dig into this too much, just wanted to log it. 

If I run limit before collect, it returns 5 rows
```ruby
files = %w(file1.parquet file2.parquet)
lazy_frames = files.map { |file| Polars.scan_parquet(file) }
combined_lazy_df = Polars.concat(lazy_frames)
combined_lazy_df.limit(100).collect
=> shape: (5, 101)
```

If I run limit after collect, it returns the proper limit, but is of course slower
```ruby
files = %w(file1.parquet file2.parquet)
lazy_frames = files.map { |file| Polars.scan_parquet(file) }
combined_lazy_df = Polars.concat(lazy_frames)
combined_lazy_df.collect.limit(100)
=> shape: (100, 101)
```

Maybe there's something I'm missing about Polars but the behavior seems off right?

**Comment by ankane** [comment]
Hey @brettshollenberger, thanks for reporting! Looks like a mistake when porting the method (and didn't have any examples to catch it). Fixed in the commit above.

**Comment by brettshollenberger** [comment]
Killer, thank you!
