### ISSUE TITLE
Feature: strip values during reading of CSV

### ISSUE THREAD

**Issue by gsinclair** [ankane/ruby-polars#90]
When using `Polars.read_csv` I would like to be able to pass an argument `strip: true` so that all individual values are string-stripped before processing.

Reason: I have some 'NA' strings which I treat as null values (via the `null_values` argument). This has worked beautifully. But now I inherited a CSV file that has 'NA ' somewhere in it (note the space) and this is not being treated as a null value and is causing an error because it can't be cast to f64.

I prefer to solve a problem myself instead of asking for a library to change. But I don't really get to do any pre-processing on data before calling `read_csv`. Or it would be a bit awkward to do so.

Also, I think it is a pretty logical thing to do. In general, surrounding whitespace should not affect conversion from string to value (int, float, date, etc.). So it should not affect conversion to null either. `strip` would default to false for performance and backward-compatibility reasons, but it would be a useful tool to have.

Thanks heaps for this awesome library.

**Comment by ankane** [comment]
Hi @gsinclair, this would need to be implemented in [Polars](https://github.com/pola-rs/polars) first, so you'll want to submit it there.
