### ISSUE TITLE
Newbie Question on plotting

### ISSUE THREAD

**Issue by ausangshukla** [ankane/ruby-polars#91]
df = Polars::DataFrame.new({"a" => ["one", "two", "three"], "b" => [1, 2, 3], "c" => ["group1", "group1", "group2"]})
df.plot("a", "b", type: "line", group: "c")

This works well

df = Polars::DataFrame.new({"a" => ["one", "two", "three"], "b" => [1, 2, 3], "c" => ["group1", "group1", "group2"], "d"=>[1,2,3,4,5] })

How to plot this, as we have an additional col d?

Thanks

**Comment by ankane** [comment]
Hi @ausangshukla, plotting only supports 2 - 3 columns. You can either transform the data frame to get it to that number of columns, or for more advanced plotting, use [Vega.rb](https://github.com/ankane/vega-ruby) directly.
