### ISSUE TITLE
Request: Add support for verbose thread information and configuration

### ISSUE THREAD

**Issue by DeflateAwning** [ankane/ruby-polars#92]
It would be awesome if you could add the `pl.thread_pool_size()` method (https://docs.pola.rs/api/python/stable/reference/api/polars.thread_pool_size.html).

It would also be great if you could support setting the `POLARS_MAX_THREADS` configuration (e.g., via an environment variable). It's not currently in [the list of supported environment variables](https://www.rubydoc.info/gems/polars-df/Polars/Config).

**Comment by ankane** [comment]
Added in the commit above.

**Comment by DeflateAwning** [comment]
Thank you!
